Content_Management/urls.py
from django.urls import path,re_path
from django.conf.urls import include
from Content_Management.views import *
from . import views

app_name='Article'
urlpatterns = [
    path('/all',views.AllArticles,name="all articles"),
    path('/<str:tag>/',views.ListOfArticles,name="similar_articles"),
    path('/',views.ContentBasedOnUser,name="content for current user"),
    path('/submit_report',views.model_form_upload,name='submit_report'),
    path('/MyProfile',views.MyProfile,name='myprofile'),
    path('/Medications',views.medication,name="medicationcalendar"),
    path('/appointment', views.appointment, name="appointmentcalendar"),
    path('/FamilyHealth',views.Get,name='FamilyHealth'),
    path("/allac",views.AllActivities,name="all activities")
]

HML/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView
from Content_Management.views import *
from Patients_Records.views import *
from Patients_Heart_Model.views import MemberAutocomplete
admin.site.site_header = 'Health Care ML admin'

admin.site.site_title = 'HML admin'
admin.site.site_url = 'http://HML.com/'
admin.site.index_title = 'HML administration'
urlpatterns = [
    path('admin_tools_stats/', include('admin_tools_stats.urls')),
    path('admin_tools/', include('admin_tools.urls')),
    path('Patients_Records', include('Patients_Records.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('Content_Management',include('Content_Management.urls',namespace="CM")),
    path('Patients_Heart_Model',include('Patients_Heart_Model.urls',namespace="Patients_HM")),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path('detail/<slug:slug>/',ArticleDetailView.as_view(), name='single_article'),
    path('dailydiet',include('dailydiet.urls',namespace="Diet")),
    path('patient-autocomplete',MemberAutocomplete.as_view(),name='patient-autocomplete'),



]

Patients_Heart_Model/urls.py
from django.urls import path,reverse
from . import views
from .views import *
app_name='patients_heart_model'
urlpatterns = [
    path('/<int:user_id>', views.update_profile, name='index'),
    path('/AddFamily',views.family_page,name='familypage'),
    
    ]

Content_Management/models.py
from django.db import models
from taggit.managers import TaggableManager
from hitcount.models import  HitCount
from hitcount.views import HitCountMixin
from django.contrib.contenttypes.fields import GenericRelation
from django.utils.encoding import python_2_unicode_compatible
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# seed the pseudorandom number generator
from random import seed
from random import random


@python_2_unicode_compatible
class Article(models.Model,HitCountMixin):
    title=models.CharField(max_length=120)
    body=models.TextField()
    tags=TaggableManager(blank=True)
    seed(1)
    slug = models.SlugField(unique=True, max_length=200,default=random())
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',
     related_query_name='hit_count_generic_relation')
    def __str__(self):
        return self.title
    

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super(Article, self).save(*args, **kwargs)

class Report(models.Model):
    report=models.FileField(upload_to="reports/")
    uploaded_by=models.ForeignKey(User,on_delete=models.CASCADE,blank=True)
    upload_date=models.DateTimeField(auto_now_add=True)
    def __str__(self):        
        return str(self.id)

def post_save_receiver(sender, instance, created, **kwargs):
    pass

post_save.connect(post_save_receiver, sender=settings.AUTH_USER_MODEL)

class Activity(models.Model,HitCountMixin):
    Title=models.CharField(max_length=120)
    description=models.CharField(max_length=120)
    tags=TaggableManager(blank=True)
    date=models.DateField()
    def __str__(self):        
        return str(self.Title)

Content_Management/forms.py
from django import forms
from .models import Report
class ReportForm(forms.ModelForm):
    class Meta:
        model=Report
        fields=('report',)
    def uploadeby(self):
        if not self.cleaned_data['uploaded_by']:
            return User()
        return self.cleaned_data['uploaded_by']

Content_Management/views.py
from django.shortcuts import render, get_object_or_404,render_to_response,redirect
from taggit.models import Tag
from .models import *
from django.http import HttpResponse,HttpResponseRedirect
from hitcount.views import HitCountDetailView
from django.conf.urls import include
from django.views.generic.list import ListView
from .forms import *
from django.core.files.storage import FileSystemStorage
from Patients_Records.models import *
from Patients_Heart_Model.models import * 
from dailydiet.models import *
import pandas as pd
from django_pandas.io import read_frame
def ListOfArticles(request,tag):
    #list articles that contain a certain tag
    tags = Tag.objects.filter().values_list('name')
    
    articles = Article.objects.filter(tags__name__icontains=tag)
    context = {
        
        'articles':articles,
    }
    return render(request, 'Content_Management/listofarticles.html', context)

def AllArticles(request):
    articles=Article.objects.all()
    
    context = {
        
        'articles':articles,
    }
    return render(request, 'Content_Management/listofarticles.html', context)
def ContentBasedOnUser(request):
    tag=request.user.patient.patient_basic_record_set.last().TenYearCHD
    if tag:
        tag="TenYearCHD"
        articles = Article.objects.filter(tags__name__exact=tag)
    else :
        tag="GeneralContent"
        articles=Article.objects.filter(tags__name__exact=tag)
     #request.user=>currentuser |patient=>1-to-1 field|    
    
    context = {
        
        'articles':articles,
    }
    return render(request, 'Content_Management/listofarticles.html', context)


class ArticleListView(ListView):
    model = Article
    context_object_name = 'articles'
    template_name = 'Content_Management/listofarticles.html'
    
class ArticleDetailView(HitCountDetailView):
    model = Article
    template_name = 'Content_Management/article.html'
    context_object_name = 'article'
    slug_field = 'slug'
    # set to True to count the hit
    count_hit = True

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        context.update({
        'popular_posts': Article.objects.order_by('-hit_count_generic__hits')[:3],
        })
        return context

def model_form_upload(request):
    if request.method=='POST':
        form=ReportForm(request.POST,request.FILES)
        if form.is_valid():
            form=form.save(commit=False)
            form.uploaded_by=request.user
            form.save()
            return redirect("CM:content for current user")
    else:
        form = ReportForm()
    
    
    return render(request, 'Content_Management/submitreport.html', {
        'form': form
    })
def MyProfile(request):
    patientID=Patient_Classified.objects.filter(user=request.user).last().id
    recordBMI=Patient_basic_record.objects.filter(Patient_ID__id=patientID).last().BMI
    Glucose=Patient_basic_record.objects.filter(Patient_ID__id=patientID).last().glucose
    totchol=Patient_basic_record.objects.filter(Patient_ID__id=patientID).last().totChol
    #correlation calculation starts here 

    qsmeals=Meal.objects.all()
    qs=Daily_Meal.objects.filter(user=request.user)
    totfat,cal,prot,react=[],[],[],[]
    for e in qs:
        fat=0
        calories=0
        protien=0
        fat=e.breakfast.fat + e.lunch.fat +e.dinner.fat
        calories=e.breakfast.calories + e.lunch.calories +e.dinner.calories
        protein=e.breakfast.protein + e.lunch.protein +e.dinner.protein
        reaction=int(e.reaction)
        react.append(reaction)
        totfat.append(fat)
        cal.append(calories)
        prot.append(protein)
    totals={'Fat':totfat,'Calories':cal,'Protein':prot}
    df=pd.DataFrame(totals)
    
    # df=df.to_html()
    react=pd.Series(react)  
    corr=df.corrwith(react)
    corr=corr.argmax()
    dailyfat=sum(totfat)
    dailyprotein=sum(prot)
    dailycalories=sum(cal)

    context={
        
        "user":request.user.first_name,
        "BMI":recordBMI,
        "glucose":Glucose,
        "totchol":totchol,
        "nutriant":corr,
        "dailyfat":dailyfat,
        "dailyprotein":dailyprotein,
        "dailycalories":dailycalories,

        }
    return render(request,'Content_Management/MyProfile.html',context)
def medication(request):
    return render(request,'Content_Management/medicationcalendar.html')
def appointment(request):
    return render(request,"Content_Management/appointmentcalendar.html")
def Get(request):
    return render(request,"Content_Management/family.html")






def AllActivities(request):
    activities=Activity.objects.all()
    
    context = {
        
        'activities':activities,
    }
    return render(request, 'Content_Management/listofactivities.html', context)

# def corrnutriants(request):
#     qsmeals=Meal.objects.all()
#     qs=Daily_Meal.objects.filter(user=request.user)
#     totfat,cal,prot,react=[],[],[],[]
#     for e in qs:
#         fat=0
#         calories=0
#         protien=0
#         fat=e.breakfast.fat + e.lunch.fat +e.dinner.fat
#         calories=e.breakfast.calories + e.lunch.calories +e.dinner.calories
#         protein=e.breakfast.protein + e.lunch.protein +e.dinner.protein
#         reaction=int(e.reaction)
#         react.append(reaction)
#         totfat.append(fat)
#         cal.append(calories)
#         prot.append(protein)
#     totals={'TotFat':totfat,'TotCalories':cal,'TotProtein':prot}
#     df=pd.DataFrame(totals)
#     # df=df.to_html()
#     react=pd.Series(react)  
#     corr=df.corrwith(react)
#     corr=corr.to_frame()
#     corr=corr.to_html()
#     return HttpResponse(corr)

Content_Management/templates/Content_Management/MyProfile.html
{% extends 'base.html' %}
{% block content %}
<html>
  <head>
   <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
   <script type="text/javascript">
      google.charts.load('current', {'packages':['gauge', 'corechart',]});
      google.charts.setOnLoadCallback(drawChart);
      google.charts.setOnLoadCallback(drawChart2);
      google.charts.setOnLoadCallback(drawChart3);
      google.charts.setOnLoadCallback(drawChart4);
      google.charts.setOnLoadCallback(drawChart5);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Label', 'Value'],
          ['Glucose', {{glucose}}],
        ]); 
        var options = {
            width: 400, height: 120,
            redFrom: 130, redTo: 350,
            yellowFrom:100, yellowTo: 130,
            minorTicks: 5,max:350
        };

        var chart = new google.visualization.Gauge(document.getElementById('chart_div'));

        chart.draw(data, options);

        setInterval(function() {
          
          chart.draw(data, options);
        }, 13000);
      }
    function drawChart4() {
        var data = google.visualization.arrayToDataTable([
          ['Label', 'Value'],
          ['BMI', {{BMI}}],
        ]); 
        var options = {
            width: 400, height: 120,
            redFrom: 32, redTo: 45,
            yellowFrom:25, yellowTo: 32,
            minorTicks: 10,max:45
        };

        var chart = new google.visualization.Gauge(document.getElementById('chart_div2'));

        chart.draw(data, options);

        setInterval(function() {
          
          chart.draw(data, options);
        }, 13000);
      }
    function drawChart5() {
        var data = google.visualization.arrayToDataTable([
          ['Label', 'Value'],
          ['Cholesterol', {{totchol}}],
        ]); 
        var options = {
            width: 400, height: 120,
            redFrom: 240, redTo: 400,
            yellowFrom:200, yellowTo: 240,
            minorTicks: 10,max:400
        };

        var chart = new google.visualization.Gauge(document.getElementById('chart_div3'));

        chart.draw(data, options);

        setInterval(function() {
         
          chart.draw(data, options);
        }, 13000);
      }
    function drawChart2() {
            // Define the chart to be drawn.
            var data = google.visualization.arrayToDataTable([
               ['Year', 'User', 'Ideal'],
               ['Protein',  {{dailyprotein}},      390],
               ['Calories',  {{dailycalories}},      400],
               ['Sugar',  1170,      440],
               ['Carbs',  1250,       480],
               ['Fat',  {{dailyfat}},      540]
            ]);

            var options = {title: 'User nutriants compared to Ideal', isStacked:true};  

            // Instantiate and draw the chart.
            var chart = new google.visualization.BarChart(document.getElementById('bar_chart'));
            chart.draw(data, options);
         }
    function drawChart3() {
        var oldData = google.visualization.arrayToDataTable([
        ['Activity', 'Duration'],
        ['Running', 256070], ['Walking', 108034],
        ['Swimming', 127101], ['hiking', 81863],
        ['Football', 74194]]);

        var newData = google.visualization.arrayToDataTable([
        ['Activity', 'Duration'],
        ['Running', 358293], ['Walking', 101265],
        ['Swimming', 172780], ['hiking', 129634],
        ['Football', 97216]]);

        var options = { pieSliceText: 'none' ,title :'Pie chart showing recommended activity inside the circle'};


        var chartDiff = new google.visualization.PieChart(document.getElementById('piechart_diff'));

        var diffData = chartDiff.computeDiff(oldData, newData);
        chartDiff.draw(diffData, options);
    }

      </script>
   <style>
   .chart{
       height: 200px;
       display: block;
   }
    </style>
    </head>
    <div class="row">
      <h1>Hi,{{user}}</h1>
    
    </div>
    <div class="chip">
        Fittnes Score 95%
      
        <i class="close material-icons">close</i>
      </div>
    <div class="chip">
          Diet Score 95%
        
          <i class="close material-icons">close</i>
        </div>
            
    <div class="row">
        <h4>BMI,GLucose and Cholesterol Indicators </h4>
        <div id="chart_div" class="chart col s4"></div>
        <div id="chart_div2" class="chart col s4"></div>
        <div id="chart_div3" class="chart col s4"></div>
    </div>
    <blockquote>
      It is noted that {{nutriant}}, cheer   you up.
    </blockquote>

    <div class="row">
        <div id="bar_chart" class = "chart col s12"></div>
    </div>


    <div class="row">
        <div id='piechart_diff' class='chart col s12'></div>
    </div>


   
</html>
{% endblock %}

Content_Management/templates/Content_Management/appointmentcalendar.html
{% extends 'base.html' %}
{% block content %}

<h1>Appointments Calendar</h1>
<body>

<div class="row">
        <div class='chart col s6'>
        <iframe src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=Asia%2FAmman&amp;src=aDExZGJ1OWIwcDA2NHFmMmthMTZmYW84ZjBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%23871111&amp;showTitle=0" style="border:solid 1px #777" width="800" height="600" frameborder="0" scrolling="no"></iframe>

        
        </div>
    
    
</div>
          
</body>


{% endblock  %}

Content_Management/templates/Content_Management/article.html
{% extends 'base.html' %}
{% load hitcount_tags %}
{% block content %}
<head>
<!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    
<script src="https://kit.fontawesome.com/beca862879.js" crossorigin="anonymous"></script>
    <style>
        body{
            max-width:80%;
            margin: 0 auto;
        }
        .article{
            padding:10px;
            border: 1px solid rgba(0,0,0,0.1)
        }
        i.fas {
            font-size: 3em;
        }
        .cat {
            width: 150px;
            display: inline-block;
        }
        .cat a{
            width: 100%;
            display: inline-block;
        }
        
        .TenYearCHD:before {
            content: "\f21e";
        }
        .reminder:before{
            content: "\f017";
        }
        .Activities:before{
            content: "\f70c";
        }
        .Medication:before{
            content: "\f46b";
        }
        .MedicalDignosis:before{
            content: "\f0f0";
        }
        .Obesity:before{
            content: "\f496";
        }
        .diabetes:before{
            content: "\f48e";
        }
        .GeneralContent:before {
            content: "\f481"
        }


    </style>
</head>
<body>

<div class="article card horizontal">
        <div class="card-stacked">
            <div class="card-content">
                <h1>
                    {% block title %}
                        <a>{{ article.title }}</a>  
                    {% endblock %}
                </h1>
                {% block content1 %}
                    <p>
                        {{ article.body }}
                    </p>
                {% endblock %}
            </div>
            <div class="card-action">
                {% for tag in article.tags.all %}
                <div class="cat">
                    <i class="fas {{ tag }}"></i>
                    <a href="#"> #{{ tag }} </a>
                </div>    
                {% endfor %} 
            </div>  
            Views: {% get_hit_count for article %}
        </div> 
    </div>
    
</body>
{% endblock %}

Content_Management/templates/Content_Management/discretebarchart.html
{% load static %}

{% load nvd3_tags %}
<head>
     {% include_chart_jscss %}
    {% load_chart charttype chartdata "discretebarchart_container" %}
</head>
<body>
    <h1>Bar chart of articles views </h1>
    {% include_container "discretebarchart_container" 600 800 %}
</body>

Content_Management/templates/Content_Management/family.html
{% extends 'base.html' %}
{% block content %}
<style>
.card .card-image {
    height: 160px;
    overflow: hidden;
}
</style>
<div class="row"><h1>Family Health</h1></div>

<div class="row">
        <div class="col s12 m4">
          <div class="card">
            <div class="card-image">
              <img src="https://image.shutterstock.com/image-photo/portrait-beautiful-senior-woman-white-260nw-552965095.jpg">
              <span class="card-title">Wife Amira</span>
            </div>
            <div class="card-content">
              <p>I am a very simple card. </p>
            </div>
            <div class="card-action">
                    <div class="chip">
                            Fittnes Score 95%
                          
                            <i class="close material-icons">close</i>
                          </div>
                        <div class="chip">
                              Diet Score 95%
                            
                              <i class="close material-icons">close</i>
                            </div>
            </div>
          </div>
        </div>
        <div class="col s12 m4">
                <div class="card">
                  <div class="card-image">
                    <img src="https://image.shutterstock.com/image-photo/portrait-young-man-crossed-hands-260nw-582575041.jpg">
                    <span class="card-title">Son Hassan</span>
                  </div>
                  <div class="card-content">
                    <p>I am a very simple card. </p>
                  </div>
                  <div class="card-action">
                          <div class="chip">
                                  Fittnes Score 95%
                                
                                  <i class="close material-icons">close</i>
                                </div>
                              <div class="chip">
                                    Diet Score 95%
                                  
                                    <i class="close material-icons">close</i>
                                  </div>
                  </div>
                </div>
              </div>
              <div class="col s12 m4">
                    <div class="card">
                      <div class="card-image">
                        <img src="https://ichef.bbci.co.uk/news/660/cpsprodpb/1646D/production/_105854219_megan.jpg">
                        <span class="card-title">Daughter Noor</span>
                      </div>
                      <div class="card-content">
                        <p>I am a very simple card. </p>
                      </div>
                      <div class="card-action">
                              <div class="chip">
                                      Fittnes Score 95%
                                    
                                      <i class="close material-icons">close</i>
                                    </div>
                                  <div class="chip">
                                        Diet Score 95%
                                      
                                        <i class="close material-icons">close</i>
                                      </div>
                      </div>
                    </div>
                  </div>
      </div>

<a href="{% url "Patients_HM:familypage" %}" class="waves-effect waves-light btn-large">Add Family</a>





{% endblock %}

Content_Management/templates/Content_Management/listofactivities.html
{% extends 'base.html' %}

{% block content %}
<head>
<!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    
<script src="https://kit.fontawesome.com/beca862879.js" crossorigin="anonymous"></script>

    <style>
        
        .activity{
            padding:10px;
            border: 1px solid rgba(0,0,0,0.1)
        }
        i.fas {
            font-size: 3em;
        }
        .cat {
            width: 150px;
            display: inline-block;
        }
        .cat a{
            width: 100%;
            display: inline-block;
        }
        .TenYearCHD:before {
            content: "\f21e";
        }
        .reminder:before{
            content: "\f017";
        }
        .Activities:before{
            content: "\f70c";
        }
        .Medication:before{
            content: "\f46b";
        }
        .MedicalDignosis:before{
            content: "\f0f0";
        }
        .Obesity:before{
            content: "\f496";
        }
        .diabetes:before{
            content: "\f48e";
        }
        .GeneralContent:before {
            content: "\f481"
        }
    </style>
</head>
<body>
{% for activity in activities %}
    <div class="activity card horizontal">
        <div class="card-stacked">
            <div class="card-content">
                <h1>
                    {% block title %}
                        <a>{{ activity.Title }}</a>  
                    {% endblock %}
                </h1>
                {% block content1 %}
                    <p>
                        {{ activity.description }}
                    </p>
                     {% endblock %}
            </div>
            <div class="card-action">
                {% for tag in activity.tags.all %}
                <div class="cat">
                    <i class="fas {{ tag }}"></i>
                    <a href="#"> #{{ tag }} </a>
                </div>    
                {% endfor %} 
            </div>  
            
        </div> 
    </div>
       
       
{% endfor %}
</body>
{% endblock %}

Content_Management/templates/Content_Management/listofarticles.html
{% extends 'base.html' %}
{% load hitcount_tags %}
{% block content %}
<head>
<!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    
<script src="https://kit.fontawesome.com/beca862879.js" crossorigin="anonymous"></script>

    <style>
        
        .article{
            padding:10px;
            border: 1px solid rgba(0,0,0,0.1)
        }
        i.fas {
            font-size: 3em;
        }
        .cat {
            width: 150px;
            display: inline-block;
        }
        .cat a{
            width: 100%;
            display: inline-block;
        }
        .TenYearCHD:before {
            content: "\f21e";
        }
        .reminder:before{
            content: "\f017";
        }
        .Activities:before{
            content: "\f70c";
        }
        .Medication:before{
            content: "\f46b";
        }
        .MedicalDignosis:before{
            content: "\f0f0";
        }
        .Obesity:before{
            content: "\f496";
        }
        .diabetes:before{
            content: "\f48e";
        }
        .GeneralContent:before {
            content: "\f481"
        }
    </style>
</head>
<body>
{% for article in articles %}
    <div class="article card horizontal">
        <div class="card-stacked">
            <div class="card-content">
                <h1>
                    {% block title %}
                        <a href="{% url 'single_article' slug=article.slug %}">{{ article.title }}</a>  
                    {% endblock %}
                </h1>
                {% block content1 %}
                    <p>
                        {{ article.body }}
                    </p>
                {% endblock %}
            </div>
            <div class="card-action">
                {% for tag in article.tags.all %}
                <div class="cat">
                    <i class="fas {{ tag }}"></i>
                    <a href="#"> #{{ tag }} </a>
                </div>    
                {% endfor %} 
            </div>  
            Views: {% get_hit_count for article %}
        </div> 
    </div>
       
{% endfor %}
</body>
{% endblock %}

Content_Management/templates/Content_Management/medicationcalendar.html
{% extends 'base.html' %}
{% block content %}

<h1>Medications Calendar</h1>
<body>
<iframe class= 'calendar' src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=Asia%2FAmman&amp;src=bTY3dDNkOTRraXUwbHExZmp0YW5yNG01bnNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%23402175&amp;showTitle=0&amp;showCalendars=0&amp;showTabs=1&amp;mode=WEEK" style="border:solid 1px #777" width="800" height="600" frameborder="0" scrolling="no"></iframe>
</body>
{% endblock  %}}

Content_Management/templates/Content_Management/piechart.html
{% load_chart charttype chartdata "piechart_container" extra %}
{% load static %}
{% load nvd3_tags %}
<head>
    {% include_chart_jscss %}
    {% load_chart charttype chartdata chartcontainer extra %}
</head>
<body>
    <h1> Risk vs Not at Risk vs Diabetes</h1>
    {% include_container chartcontainer 600 800 %}
</body>

Content_Management/templates/Content_Management/submitreport.html
{% extends 'base.html' %}
{% block content %}
<style>

.row {
  display: flex;
  flew-wrap: wrap;
  justify-content: center;
  align-items: center;
  margin:100px;
}
</style>

<div class="row">

  
  <div class="col s12 ">
  <div>
    <h5 class="left-align">Choose a report file to upload</h5>
  </div>
        
  <form method="POST" enctype="multipart/form-data"> 
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn waves-effect waves-light">Upload</button>
  </form>
      <p><a href="{% url "CM:content for current user" %}">Return to home</a></p>

  </div>

   </div>

{% endblock %}

Content_Management/templates/Content_Management/test.html
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Test {% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {{test}}
    {% endblock %}
  </main>
</body>
</html>