Content_Management/urls.py
from django.urls import path,re_path
from django.conf.urls import include
from Content_Management.views import *
from . import views

app_name='Article'
urlpatterns = [
    path('/all',views.AllArticles,name="all articles"),
    path('/<str:tag>/',views.ListOfArticles,name="similar_articles"),
    path('/',views.ContentBasedOnUser,name="content for current user"),
    path('/submit_report',views.model_form_upload,name='submit_report'),
    path('/MyProfile',views.MyProfile,name='myprofile'),
    path('/Medications',views.medication,name="medicationcalendar"),
    path('/appointment', views.appointment, name="appointmentcalendar"),
    path('/FamilyHealth',views.Get,name='FamilyHealth'),
    path("/allac",views.AllActivities,name="all activities")
]

HML/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView
from Content_Management.views import *
from Patients_Records.views import *
from Patients_Heart_Model.views import MemberAutocomplete
admin.site.site_header = 'Health Care ML admin'

admin.site.site_title = 'HML admin'
admin.site.site_url = 'http://HML.com/'
admin.site.index_title = 'HML administration'
urlpatterns = [
    path('admin_tools_stats/', include('admin_tools_stats.urls')),
    path('admin_tools/', include('admin_tools.urls')),
    path('Patients_Records', include('Patients_Records.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('Content_Management',include('Content_Management.urls',namespace="CM")),
    path('Patients_Heart_Model',include('Patients_Heart_Model.urls',namespace="Patients_HM")),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path('detail/<slug:slug>/',ArticleDetailView.as_view(), name='single_article'),
    path('dailydiet',include('dailydiet.urls',namespace="Diet")),
    path('patient-autocomplete',MemberAutocomplete.as_view(),name='patient-autocomplete'),



]

dailydiet/urls.py
from django.urls import path,re_path
from django.conf.urls import include
from dailydiet.views import *
app_name='dailydiet'
urlpatterns = [
    path('/dailymealform',DietForm,name="dailymeal"),
    ]

templates/base.html
<html>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://kit.fontawesome.com/beca862879.js" crossorigin="anonymous"></script>
<script src="http://code.jquery.com/jquery-latest.min.js"></script> 

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


<body >

  <nav>
    <div class="nav-wrapper">
      <a href="#" data-target="mobile-nav" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      
      <ul class="center hide-on-med-and-down ">
        <li><a href="/Content_Management">Home</li>
        <li><a href="{% url 'CM:myprofile' %}" >My Profile</li>
        <li><a href="{% url "CM:appointmentcalendar" %}">Appointments</li>
        <li><a href="{% url "CM:medicationcalendar" %}">Medications</a></li>
        <li><a href="{% url "Diet:dailymeal" %}">Daily Diet</a></li>
        <li><a href="{% url 'CM:submit_report' %}">Submit Report</a></li>
        <li><a href="{% url 'CM:FamilyHealth' %}">Family Health</a></li>  
      </ul>
    </div>
  </nav>  

  <ul class="sidenav" id="mobile-nav">
        <li><a href="/Content_Management">Home</li>
        <li><a href="{% url 'CM:myprofile' %}" >My Profile</li>
        <li><a href="{% url "CM:appointmentcalendar" %}">Appointments</li>
        <li><a href="{% url "CM:medicationcalendar" %}">Medications</a></li>
        <li><a href="{% url "Diet:dailymeal" %}">Daily Diet</a></li>
        <li><a href="{% url 'CM:submit_report' %}">Submit Report</a></li>
        <li><a href="{% url 'CM:FamilyHealth' %}">Family Health</a></li> 
  </ul>
<script>

  $(document).ready(function(){
    $('.sidenav').sidenav();
    
  });
        


</script>


<div class = container>



 {% block content %}
 {% endblock %}
</div>
   
</body>
</html> 

templates/home.html
{% extends 'base.html' %}

{% block title %}Home page{% endblock %}

{% block content %}
<div class="row">
      <div class="col s12"> 
      {% if user.is_authenticated %}
        Hi {{ user.username }}!
        <p><a href="{% url 'logout' %}">logout</a></p>
      {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'login' %}">login</a>
      {% endif %}
      
      
       </div>
      
    </div>

{% endblock %}